#ifndef WINDOWENUMS_H
#define WINDOWENUMS_H

#include "object.h"

class IASPP_PUBLIC WindowEnums : public Object
{
public:
    enum WindowPosition
    {
        CENTERED = SDL_WINDOWPOS_CENTERED
    };

    enum WindowFlags
    {
        FULLSCREEN = SDL_WINDOW_FULLSCREEN,
        OPENGL = SDL_WINDOW_OPENGL,
        SHOWN = SDL_WINDOW_SHOWN,
        HIDDEN = SDL_WINDOW_HIDDEN,
        BORDERLESS = SDL_WINDOW_BORDERLESS,
        RESIZABLE = SDL_WINDOW_RESIZABLE,
        MINIMIZED = SDL_WINDOW_MINIMIZED,
        MAXIMIZED = SDL_WINDOW_MAXIMIZED,
        INPUT_GRABBED = SDL_WINDOW_INPUT_GRABBED,
        INPUT_FOCUS = SDL_WINDOW_INPUT_FOCUS,
        MOUSE_FOCUS = SDL_WINDOW_MOUSE_FOCUS,
        FULLSCREEN_DESKTOP = SDL_WINDOW_FULLSCREEN_DESKTOP,
        FOREIGN = SDL_WINDOW_FOREIGN,
        HIGHDPI = SDL_WINDOW_ALLOW_HIGHDPI
    };
};

#endif // WINDOWENUMS_H
